Vagrant.configure("2") do |config|
    config.vm.define "node-1" do |node1|
        node1.vm.box = "generic/alpine318"
        node1.vm.hostname = "node-1"
        node1.vm.network "private_network", ip: "192.168.56.101"
        node1.vm.network :forwarded_port, guest: 22, host: 50022
        node1.ssh.insert_key = false
    end
    config.vm.define "node-2" do |node2|
        node2.vm.box = "generic/alpine318"
        node2.vm.hostname = "node-2"
        node2.vm.network "private_network", ip: "192.168.56.102"
        node2.vm.network :forwarded_port, guest: 22, host: 50122
        node2.ssh.insert_key = false
    end
    config.vm.define "node-3" do |node3|
        node3.vm.box = "generic/alpine318"
        node3.vm.hostname = "node-3"
        node3.vm.network "private_network", ip: "192.168.56.103"
        node3.vm.network :forwarded_port, guest: 22, host: 50222
        node3.ssh.insert_key = false
    end
  end
